# Generated by Django 4.1 on 2023-10-06 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('robots', '0002_alter_robot_created_alter_robot_model_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField()),
                ('robot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='robots.robot')),
            ],
        ),
    ]
