# Generated by Django 4.1 on 2023-10-06 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='robot',
        ),
        migrations.AddField(
            model_name='stock',
            name='robot_serial',
            field=models.CharField(default='', max_length=5),
            preserve_default=False,
        ),
    ]
