# Generated by Django 4.1 on 2023-10-05 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robot',
            name='created',
            field=models.DateTimeField(verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='robot',
            name='model',
            field=models.CharField(max_length=2, verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='robot',
            name='serial',
            field=models.CharField(max_length=5, verbose_name='Серийный номер'),
        ),
        migrations.AlterField(
            model_name='robot',
            name='version',
            field=models.CharField(max_length=2, verbose_name='Версия'),
        ),
    ]
